version: 2
jobs:
  create_vpc:
    environment:
      AWS_DEFAULT_REGION: us-east-1
      TF_WORKSPACE: dev
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/project
      - run: terraform init
        #- persist_to_workspace:
        #  root: /root
        #  paths:
        #    - project

  do_next_thing:
    environment:
      X: Y
      A: B
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/project
      - run: terraform init
        #- persist_to_workspace:
        #  root: /root
        #  paths:
        #    - project

workflows:
  version: 2
  deploy:
    jobs:
      - create_vpc:
      - do_next_thing:
          requires:
            - create_vpc
